spring:
  application:
    name: product-service
    secret: asdfadls134$#@%asdfadls1234567890
    api-key: asdfadls134$#@%asdfadls1234567890

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  paths-to-match: /api/**
